branches:
  only:
    - main

environment:

  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python38-x64"

install:
  - "%PYTHON%\\python.exe -c \"import sys; print(sys.version)\""
  - "%PYTHON%\\python.exe -m pip install --upgrade pip setuptools wheel"
  - "%PYTHON%\\python.exe -m pip install ."

build: off

test_script:
  - "%PYTHON%\\python.exe -m myokit system"
  - "%PYTHON%\\python.exe -m myokit test unit"

