#
# Configuration for travis-ci continuous integration
#
sudo: required

# Test on Ubuntu 16
os: linux
dist: xenial

language: python

# Only build main and PRs
branches:
  only:
    - main

# Python version choices:
#
# 2.7.0 --> Released 2010-07-03, not tested!
# 2.7.6 --> Released 2013-11-10, earliest version testable on Travis
#       --> Version shipped with Ubuntu LTS 14.04 (supported until 2019)
# 2.7   --> Latest 2.7 version. At the moment 2.7.14 on travis (2018-10-31)
# 3.0-3.3 --> Bad initial versions of Python 3; Not supported
# 3.4     --> No longer supported by pip (2019-03)
# 3.5-3.8 --> Works

matrix:
    # Always put true env variable first, for nicer overview on travis website
    include:
        # Unit tests on OS/X, running first because this one's slow
        - os: osx
          osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
          language: shell
          env:
            - MYOKIT_UNIT=true
        # Style checking
        - python: "3.8"
          env:
            - MYOKIT_STYLE=true
        # Doctests
        - python: "3.8"
          env:
            - MYOKIT_DOC=true
        # Cover checking
        - python: "3.8"
          env:
            - MYOKIT_COVER=true
        # Unit tests on Ubuntu
        - python: "2.7.6"
          dist: trusty
          env:
            - MYOKIT_UNIT=true
        - python: "2.7"
          env:
            - MYOKIT_UNIT=true
        - python: "3.5"
          env:
            - MYOKIT_UNIT=true
        - python: "3.6"
          env:
            - MYOKIT_UNIT=true
        - python: "3.7"
          env:
            - MYOKIT_UNIT=true
        - python: "3.8"
          env:
            - MYOKIT_UNIT=true
        # Basic install test
        - python: "3.8"
          env:
            - MYOKIT_BASIC=true
            - MYOKIT_UNIT=true

# Install CVODE dependencies
before_install:
  # Ubuntu
  # Python packages can be installed here but won't work (tests run in virtualenv)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update;
      sudo apt-get install -y libsundials-serial-dev;
    fi;
  # OS/X
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update-reset;
      brew install sundials;
    fi;

# Install Myokit and extra testing dependencies
install:
  - pip install --upgrade pip;
  - if [[ $MYOKIT_BASIC == true ]]; then pip install .; else pip install .[optional]; fi;
  - if [[ $MYOKIT_COVER == true ]]; then pip install coverage codecov; fi;
  - if [[ $MYOKIT_STYLE == true ]]; then pip install .[dev]; fi;
  - if [[ $MYOKIT_DOC == true ]]; then pip install .[docs,gui]; fi;

# Show system information
before_script:
- python -m myokit system

# Run tests
script:
  - if [[ $MYOKIT_UNIT == true ]]; then python -m myokit test unit; fi;
  - if [[ $MYOKIT_COVER == true ]]; then coverage3 run -m myokit test unit; fi;
  - if [[ $MYOKIT_STYLE == true ]]; then
        python -m flake8 --version;
        python -m flake8;
    fi;
  - if [[ $MYOKIT_DOC == true ]]; then
        python -m myokit test doc;
    fi;

# Compile coverage report
after_success:
  - if [[ $MYOKIT_COVER == true ]]; then codecov; fi;

# Send notifications
notifications:
  email:
    recipients:
    - michael.clerx@nottingham.ac.uk
